version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=iw43-symfony
    - POSTGRES_USER=api-plateform
    - POSTGRES_PASSWORD=lmdpe
    ports:
    - "5432:5432"
volumes:
  db-data: {}